# Generated by Django 3.1.5 on 2021-01-19 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210119_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 15, 42, 42, 882541)),
        ),
    ]
